version: "3.1"

services:
  isx-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - MSSQL_SA_PASSWORD=Yourpassword123!
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
    container_name: isx-db
    volumes:
      - sqlvolume:/var/opt/mssql

volumes:
  sqlvolume:
